create table smlogs 
	(id UInt16,
	timestamp String,
	level String,
	sys String,
	mrf String,
	user String,
	script_id String,
	script_name String,
	script_key String,
	script_version Decimal (4, 1),
	script_process String,
	action String,
	action_entity String,
	action_id String,
	action_data String,
	message String,
	script_step_id String,
	script_step_name String,
	current_script_name String,
	current_script_key String,
	current_script_version Decimal (4, 1),
	block_type String,
	parameters String,
	timezone String,
	communication_id Decimal (9, 1),
	communication_number UInt32,
	integration_service_id String,
	duration Decimal (9, 6),
	client_mrf String,
	session String,
	script_owner String,
	current_script_owner String,
	script_responsible String,
	current_script_responsible String,
	crm_departament String)
order by id