INSERT INTO smboard (timestamp,
	user,
	communication_number,
	communication_id,
	script_id,
	script_name,
	mrf,
	client_mrf,
	script_owner,
	current_script_owner,
	script_responsible,
	current_script_responsible,
	crm_departament,
	ACCOUNT_NUMBER,
	CALLER_ID,
	COMMUNICATION_THEME,
	COMMUNICATION_DETAIL,
	COMMUNICATION_RESULT)
SELECT 
	toDateTime(floor(toInt64(toFloat64(s.timestamp)))),
	s.user,
	s.communication_number,
	s.communication_id,
	s.script_id,
	s.script_name,
	s.mrf,
	s.client_mrf,
	s.script_owner,
	s.current_script_owner,
	s.script_responsible,
	s.current_script_responsible,
	s.crm_departament,
	JSONExtractString(s.parameters, 'ACCOUNT_NUMBER') as ACCOUNT_NUMBER,
	JSONExtractString(s.parameters, 'CALLER_ID') as CALLER_ID,
	JSONExtractString(s.parameters, 'COMMUNICATION_THEME') as COMMUNICATION_THEME,
	JSONExtractString(s.parameters, 'COMMUNICATION_DETAIL') as COMMUNICATION_DETAIL,
	JSONExtractString(s.parameters, 'COMMUNICATION_RESULT') as COMMUNICATION_RESULT
FROM smlogs s
